name: "CI"

on:

  pull_request:
  push:

jobs:

  php8-checks:
    strategy:
      matrix:
        version: ['8.2', '8.3']
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build docker image
      uses: docker/build-push-action@v5
      with:
        push: false
        target: test-runner
        tags: php${{ matrix.version }}-checks
        build-args: PHP_VERSION=${{ matrix.version }}
    - name: Run tests
      run: docker run --rm -v ./:/var/www/html/public/build php${{ matrix.version }}-checks sh -c "composer test:all"
    - name: Generate coverage badge
      uses: timkrase/phpunit-coverage-badge@v1.2.1
      with:
        coverage_badge_path: 'badge-coverage.svg'
        push_badge: true
        repo_token: ${{ secrets.GITHUB_TOKEN }}
